name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy to Server
        run: |
          rsync -r --exclude='.git' "${{ github.workspace }}/html/" root@68.183.83.66:/var/www/jai.hopto.org/html/wordpress
        env:
          SSH_USER: root
          SERVER_IP: 68.183.83.66
          DESTINATION_PATH: /var/www/jai.hopto.org/html/wordpress
